name: micro_skill_decay_detector
description: "The Micro-Skill Decay Detector is a mobile application designed to help users track, manage, and retain small but important skills over time."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png

