// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB92mPF6k9yP1m0FtR6gai1bJSFV7psB2c',
    appId: '1:483787424425:web:fbea8882e7473a73c09fb8',
    messagingSenderId: '483787424425',
    projectId: 'micro-skill-decay-detector',
    authDomain: 'micro-skill-decay-detector.firebaseapp.com',
    storageBucket: 'micro-skill-decay-detector.firebasestorage.app',
    measurementId: 'G-C4YXYFBG6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUzTXVWubyKHhUWZSfxIbTa9K6MEhHJWw',
    appId: '1:483787424425:android:c9e2cb142cdf902cc09fb8',
    messagingSenderId: '483787424425',
    projectId: 'micro-skill-decay-detector',
    storageBucket: 'micro-skill-decay-detector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8DSijbutSg6VCE59lN9v54Vm76Zs-RvM',
    appId: '1:483787424425:ios:ccafae014e85d22fc09fb8',
    messagingSenderId: '483787424425',
    projectId: 'micro-skill-decay-detector',
    storageBucket: 'micro-skill-decay-detector.firebasestorage.app',
    iosBundleId: 'com.example.microSkillDecayDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8DSijbutSg6VCE59lN9v54Vm76Zs-RvM',
    appId: '1:483787424425:ios:ccafae014e85d22fc09fb8',
    messagingSenderId: '483787424425',
    projectId: 'micro-skill-decay-detector',
    storageBucket: 'micro-skill-decay-detector.firebasestorage.app',
    iosBundleId: 'com.example.microSkillDecayDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB92mPF6k9yP1m0FtR6gai1bJSFV7psB2c',
    appId: '1:483787424425:web:8fdb6d94903ab966c09fb8',
    messagingSenderId: '483787424425',
    projectId: 'micro-skill-decay-detector',
    authDomain: 'micro-skill-decay-detector.firebaseapp.com',
    storageBucket: 'micro-skill-decay-detector.firebasestorage.app',
    measurementId: 'G-H26SLSBBJ7',
  );
}
